[package]
name = "project-euler"
version = "0.1.0"
authors = ["Do Nhat Minh <minhnhdo@gmail.com>"]
edition = "2021"
default-run = "usage"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
say-number = "1"
